### ISSUE TITLE
Piggybanks on server still crashes when opening gui and using latest version

### ISSUE THREAD

**Issue by zachsai** [wildcardgamez/PiggyBanks#1]
https://pastebin.com/AEgTmJMP

**Comment by wildcardgamez** [comment]
Truly a brush moment... I'll look into it...

**Comment by wildcardgamez** [comment]
https://github.com/wildcardgamez/PiggyBanks/commit/43fc6dd366fae9daac7ede18c64bef2c03f8c11f
might be fixed lmk, uploading to forge as 1.0.3 soon

**Comment by zachsai** [comment]
> [43fc6dd](https://github.com/wildcardgamez/PiggyBanks/commit/43fc6dd366fae9daac7ede18c64bef2c03f8c11f)
> might be fixed lmk, uploading to forge as 1.0.3 soon

ill test it right when you upload. You can send me the jar before it gets approved if you want me to do some server testing

**Comment by wildcardgamez** [comment]
I can't find a way to send it from github, I'm uploading 1.0.2, which is the version XD should be fixed in that, if it isn't just report another issue
